// ... existing code ...
function HomePage({ session, stations, loading, handleSignOut, navigateTo }) {
  // Debugging log for HomePage
  console.log('HomePage rendered. Session:', session ? session.user.email : 'No session');
  // ... existing code ...
}
export default HomePage;
// ... existing code ...
